# Generated by Django 3.0.8 on 2020-07-20 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(help_text='A human readable name for this shortened URL', max_length=128, verbose_name='Entry Name')),
                ('full_url', models.URLField(help_text='The full URL that will be redirected to', max_length=512, unique=True, verbose_name='Full URL')),
                ('shortened_url_slug', models.SlugField(help_text='The shortened version of the URL', max_length=64, unique=True, verbose_name='Shortened URL')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
